name: build-windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
   #This is a simple build for Windows OS.
    runs-on: windows-2016
    steps:
    
    #This checkout the branch at github workspace $GITHUB_WORKSPACE.
    - name: Checkout source
      uses: actions/checkout@v2
    
    - name: Build Logger
      #This can be any cmd/Developer cmd etc.
      shell: cmd
      #Here write all the commands required to build the lib. Use pipe  (|) at the begining of run action if multiple commands are there. 
      run: | 
        mkdir build
        cd build
        cmake -G "Visual Studio 15 2017 Win64" -L ..
        cmake --build . --clean-first --config Release 
    
